Update to the latest consensus and ledger lib versions.
input-output-hk/cardano-explorer pull request #272
Opened 2020-02-21 00:58 UTC by dcoutts

The most significant change comes from a change in the consensus lib's representation of the block number at the genesis. It now uses WithOrigin BlockNo to represent the fact that the genesis itself does not have a block number.

Also one small bug fix: Fix `getCurrentTipBlockNo` to return the block number

It was accidentally using the slot number. This was not all that significant because the only thing it was being used for was to determine how much pipelining to do in the local protocol communicating
with the node.

And one small refactoring:  Minor type clarification: use Tip type

The plugin API for inserting a block takes a block and the server's current tip block number. But since it uses the types ByronBlock and BlockNo, it's not immediately clear that this is the BlockNo of the tip rather than a plausible first guess which is that it's the block number of te block being inserted.

To avoid this danger of confusion, switch the type from BlockNo to the type Tip ByronBlock. Then the type makes clear that it is the tip and not about the block itself. It is of course still possible to get the block number from the tip.

2020-02-21 05:31 UTC, erikd requested changes
This passes CI, but it currently does not connect to the node the way it should.

This should not be merged until this is investigated and fixed.

2020-02-21 06:39 UTC, erikd commented
The code in this PR works when connecting to a node built from `cardano-node@123476bcfbad998d61f4fd4474cdfb342617da9c`, but fails when connecting to `cardano-node@1ef04c946bfce4b6545d3c138e6eb2881c4a48cf` with
```
[explorer-db-node:Info:1] [2020-02-21 06:38:43.15 UTC] localInitiatorNetworkApplication: connecting to node via "../cardano-node/state-node-mainnet/socket"
[explorer-db-node.ErrorPolicy:Warning:1] [2020-02-21 06:38:43.15 UTC] {"event":"ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 4>: does not exist (Connection r
efused))) 20s 20s","kind":"ErrorPolicyTrace","address":"../cardano-node/state-node-mainnet/socket"}
```

2020-02-26 14:04 UTC, coot commented
@erikd that's quite old version of the `cardano-node`. I just tried with the tip of the `mrBliss/update-ouroboros-network-20200219` in `cardano-node` repo (being borsed now), which contains latest updates from `ouroboros-network`.

By enabling some tracers I see this:
```
[explorer-db-node:Info:1] [2020-02-26 13:56:53.27 UTC] localInitiatorNetworkApplication: connecting to node via "../cardano-node/socket/mainnet-socket"
Mux ConnectionId {localAddress = , remoteAddress = /home/coot/clients/iohk/cardano-haskell/cardano-node/socket/mainnet-socket} Recv MsgAcceptVersion NodeToClientV_1 (TInt 764824073)
[explorer-db-node:Info:36] [2020-02-26 13:56:53.27 UTC] Starting chainSyncClient
```

So the `cardano-explorer-node` connects and runs fine.

2020-02-26 20:27 UTC, erikd commented
That version of node was from Feb 16th, which at the time I made that comment was only 5 days old.

I will update everything and try again.

2020-02-26 22:53 UTC, erikd commented
I have validated that this works correctly.

The problem I was having in https://github.com/input-output-hk/cardano-explorer/pull/272#issuecomment-589520485 was due to trying to use an old/stale socket file left over from after a renaming of the socket in the node repo

2020-02-26 22:53 UTC, merged