implement /api/supply/ada
input-output-hk/cardano-explorer pull request #33
Opened 2019-08-27 17:34 UTC by cleverca22

2019-08-27 20:35 UTC, erikd commented on cardano-explorer-db/src/Explorer/DB/Query.hs
> +queryTotalSupply :: MonadIO m => ReaderT SqlBackend m Micro
Why do we now have two versions of this function, with the same name, one in my code and one on your code?

DRY (don't repeat yourself) is an important concept in software engineering.

I suggest that you rename yours to `queryTotalSupplyAda` and have it call mine, doing a conversion from lovelace to Ada.

2019-08-27 20:35 UTC, erikd commented on cardano-explorer-db/src/Explorer/DB/Query.hs
> +    unWibble :: Maybe (Value (Maybe Micro)) -> Micro
This is just a copy/pasted verison of mine. However, mine has changed. It got a far better name, and was make into a top level function that is used twice in the same file.

Making this code long term maintainable should be an important consideration for any code we write.

2019-08-27 20:35 UTC, erikd commented on cardano-explorer-db/src/Explorer/DB/Query.hs
> +queryTotalSupply :: MonadIO m => ReaderT SqlBackend m Micro
These is even a compelling argument to be made that this version should be the only version and replace the one in my code.

2019-08-28 07:02 UTC, erikd requested changes

2019-08-28 07:02 UTC, erikd commented on cardano-explorer-db/src/Explorer/DB/Types.hs
> +{-# LANGUAGE OverloadedStrings   #-}
Excess whitespace wibbles.

2019-08-28 07:02 UTC, erikd commented on cardano-explorer-db/src/Explorer/DB/Types.hs
> +    -- https://github.com/bos/aeson/issues/227#issuecomment-245400284
Why is that comment there? It points to an issue from 2014. There have been multiple Aeson major versions released since then.

2019-08-28 07:02 UTC, erikd commented on cardano-explorer-db/src/Explorer/DB/Types.hs
> +    -- https://github.com/bos/aeson/issues/227#issuecomment-245400284
Ah so that comment came from the old code. We should delete it, but make sure we are using the currently accepted way of doing that encodng.

2019-08-28 07:02 UTC, erikd commented on cardano-explorer-db/src/Explorer/DB/Types.hs
> +        showFixed True ada   -- convert Micro to String chopping off trailing zeros
Pretty sure that can just be done as:
```
    Aeson.String $ Text.pack (showFixed True ada)
```
Where `String` is the `Text -> Value` constructor.

2019-08-28 07:40 UTC, cleverca22 commented on cardano-explorer-db/src/Explorer/DB/Types.hs
> +        showFixed True ada   -- convert Micro to String chopping off trailing zeros
`String` results in it encoding as `{"Right":"123.456789"} ` which changes the type
`Number` results in it encoding as `{"Right":7.3112484749601107e10}` which may be valid, but is drastically different from the original format
`unsafeToEncoding` results in it encoding as `{"Right":73112484749.601107}` which most closely matches the old api we are trying to maintain compatability with

2019-08-28 21:14 UTC, erikd approved these changes

2019-08-29 07:13 UTC, merged