Nix revamp
input-output-hk/cardano-explorer pull request #47
Opened 2019-09-06 13:49 UTC by manveru

2019-09-09 00:56 UTC, erikd commented
When you rebase this against master its probably worth squashing this down to a single commit.

2019-09-10 15:28 UTC, cleverca22 requested changes

2019-09-10 15:28 UTC, cleverca22 commented on nix/nixos/cardano-explorer-options.nix
> +        The directory containing the migrations.
the description of this option doesnt match up with the name

2019-09-10 15:28 UTC, cleverca22 commented on nix/nixos/cardano-explorer-service.nix
> +      uid = 10017;
does the uid/gid need to be static? it would have less chance of conflict if it was just dynamically assigned on first deploy

2019-09-10 15:28 UTC, cleverca22 commented on nix/nixos/cardano-explorer-service.nix
> +          ${cardano-explorer}/bin/cardano-explorer
this service conflicts with `systemd.services.cardano-exporter`
the name implies it does the same thing, but the .script does the same thing as `cardano-explorer-webapi`

2019-09-10 15:28 UTC, cleverca22 commented on nix/nixos/cardano-exporter-options.nix
> +  inherit (commonLib.pkgs.lib) types mkOption;
should also be able to use plain `inherit (lib) types mkOption;`

2019-09-10 15:28 UTC, cleverca22 commented on nix/nixos/cardano-exporter-options.nix
> +{ config, lib, pkgs, ... }:
the `mkMerge` and `environment` options are missing, and those helped simplify configuring things

2020-01-16 15:45 UTC, closed without merging