further improve the docker image
input-output-hk/cardano-explorer pull request #67
Opened 2019-09-27 23:34 UTC by cleverca22

2019-09-29 23:50 UTC, erikd commented
Need to apply the patch in the CI artifacts to upate the `cabal.project` file.

2019-10-07 05:23 UTC, disassembler approved these changes
looks great! Just some minor changes.

2019-10-07 05:23 UTC, disassembler commented on Dockerfile
> +FROM ubuntu
ubuntu:18.04

2019-10-07 05:23 UTC, disassembler commented on docker/default.nix
> +      redirectURL = "http://localhost.earthtools.ca/oauth2/callback";
we shouldn't reference your personal domain here

2019-10-07 05:23 UTC, disassembler commented on docker/default.nix
> +        emailDomain = "iohk.io";
shouldn't reference iohk.io google domain either.

2019-10-07 05:24 UTC, disassembler requested changes

2019-10-07 05:24 UTC, disassembler commented on docker/default.nix
> +  '';
this should be a service in `nix/nixos`

2019-11-05 15:28 UTC, closed without merging